import Link from "next/link";
import { Award, ExternalLink, Pencil, Plus, Trash2 } from "lucide-react";
import { deleteCertificationAction } from "@/app/admin/actions";
import { requireAdmin } from "@/lib/admin-auth";
import { getAllCertifications } from "@/lib/certifications";

export default async function AdminCertificationsPage({ searchParams }: { searchParams: Promise<{ saved?: string; deleted?: string; error?: string }> }) {
  await requireAdmin();
  const [certifications, params] = await Promise.all([getAllCertifications(), searchParams]);
  return <div className="mx-auto w-full max-w-6xl px-5 pb-16 pt-20 sm:px-8 lg:px-10 lg:pt-12">
    <header className="mb-8 flex flex-col gap-5 border-b border-slate-200 pb-8 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.14em] text-slate-400">Portfolio</p><h1 className="mt-2 text-3xl font-semibold tracking-tight text-slate-950">Certifications</h1><p className="mt-2 text-sm text-slate-500">Manage your credentials, certificate images, and PDF files.</p></div><Link href="/admin/certifications/new" className="inline-flex w-fit items-center gap-2 rounded-xl bg-slate-950 px-4 py-3 text-sm font-semibold text-white hover:bg-slate-800"><Plus size={17} /> New certification</Link></header>
    {(params.saved || params.deleted) && <p className="mb-5 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-medium text-emerald-700">Certification {params.deleted ? "deleted" : "saved"} successfully.</p>}{params.error && <p className="mb-5 rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm font-medium text-rose-700">{params.error}</p>}
    <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">{certifications.length ? <div className="divide-y divide-slate-100">{certifications.map((certification) => <article key={certification.id} className="flex flex-col gap-4 p-5 sm:flex-row sm:items-center sm:justify-between"><div className="flex min-w-0 items-center gap-4"><span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-slate-100 text-slate-500"><Award size={19} /></span><div className="min-w-0"><h2 className="truncate font-semibold text-slate-950">{certification.title}</h2><p className="mt-1 text-sm text-slate-500">{certification.issuer} · {certification.year}</p></div></div><div className="flex items-center gap-1"><Link href={`/admin/certifications/${certification.id}/edit`} className="rounded-lg p-2 text-slate-500 hover:bg-slate-100 hover:text-slate-950" aria-label={`Edit ${certification.title}`}><Pencil size={17} /></Link><a href={certification.pdf} target="_blank" rel="noopener noreferrer" className="rounded-lg p-2 text-slate-500 hover:bg-slate-100 hover:text-slate-950" aria-label={`View ${certification.title}`}><ExternalLink size={17} /></a><form action={deleteCertificationAction.bind(null, certification.id, certification.image, certification.pdf)}><button className="rounded-lg p-2 text-rose-500 hover:bg-rose-50" aria-label={`Delete ${certification.title}`}><Trash2 size={17} /></button></form></div></article>)}</div> : <div className="py-16 text-center"><Award className="mx-auto text-slate-300" /><p className="mt-4 text-sm text-slate-500">No certifications yet.</p></div>}</section>
  </div>;
}
