import { Code2, Film, Headphones, Layers3, ListOrdered, Palette, Pencil, Plus, Settings2, Sparkles, Trash2 } from "lucide-react";

import { createSkillAction, deleteSkillAction, updateSkillAction } from "@/app/admin/actions";
import { requireAdmin } from "@/lib/admin-auth";
import { getAllSkills, SKILL_CATEGORIES, type SkillCategory } from "@/lib/skills";

const categoryDetails: Record<SkillCategory, { description: string; icon: typeof Code2; accent: string }> = {
  Development: { description: "Technologies and engineering tools.", icon: Code2, accent: "bg-blue-50 text-blue-600" },
  "UI & Design": { description: "Design, UX, and interface capabilities.", icon: Palette, accent: "bg-violet-50 text-violet-600" },
  "Video & Content": { description: "Video production and content skills.", icon: Film, accent: "bg-rose-50 text-rose-600" },
  "Digital Support": { description: "Operational and administrative support.", icon: Headphones, accent: "bg-amber-50 text-amber-600" },
  "Workflow & Productivity": { description: "Planning, systems, and organization.", icon: Settings2, accent: "bg-emerald-50 text-emerald-600" },
  "Currently Learning": { description: "Skills currently being developed.", icon: Sparkles, accent: "bg-sky-50 text-sky-600" },
};

export default async function AdminSkillsPage() {
  await requireAdmin();
  const skills = await getAllSkills();
  const populatedCategories = SKILL_CATEGORIES.filter((category) => skills.some((skill) => skill.category === category)).length;

  return <div className="min-h-screen bg-slate-50"><div className="mx-auto w-full max-w-7xl px-5 pb-16 pt-20 sm:px-8 lg:px-10 lg:pt-12">
    <header className="mb-8 flex flex-col gap-6 border-b border-slate-200 pb-8 lg:flex-row lg:items-end lg:justify-between"><div><div className="mb-3 flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.14em] text-slate-400"><Layers3 size={14} /> About page content</div><h1 className="text-3xl font-semibold tracking-tight text-slate-950 sm:text-4xl">Skills & capabilities</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-500">Manage the skills shown in every category on your About page. Use display order to control how skills appear within a category.</p></div><a href="/about" target="_blank" rel="noopener noreferrer" className="inline-flex w-fit items-center rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-semibold text-slate-700 shadow-sm transition hover:border-slate-300 hover:text-slate-950">Preview About page ↗</a></header>

    <section className="mb-8 grid gap-4 sm:grid-cols-3"><article className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-xs font-semibold uppercase tracking-[0.12em] text-slate-400">Total skills</p><p className="mt-3 text-3xl font-semibold tracking-tight text-slate-950">{skills.length}</p><p className="mt-1 text-sm text-slate-500">Displayed on About</p></article><article className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-xs font-semibold uppercase tracking-[0.12em] text-slate-400">Active categories</p><p className="mt-3 text-3xl font-semibold tracking-tight text-slate-950">{populatedCategories}<span className="text-lg text-slate-400">/{SKILL_CATEGORIES.length}</span></p><p className="mt-1 text-sm text-slate-500">With at least one skill</p></article><article className="rounded-2xl border border-slate-200 bg-slate-950 p-5 text-white shadow-sm"><p className="text-xs font-semibold uppercase tracking-[0.12em] text-white/50">Quick tip</p><p className="mt-3 text-sm font-medium leading-6">Use 10, 20, 30 for display order so there is room to insert a skill later.</p></article></section>

    <section className="mb-8 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-100 px-5 py-4 sm:px-6"><h2 className="font-semibold text-slate-950">Add a skill</h2><p className="mt-1 text-sm text-slate-500">Add it to a category and choose where it should appear.</p></div><form action={createSkillAction} className="grid gap-4 p-5 sm:p-6 lg:grid-cols-[minmax(0,1fr)_220px_130px_auto] lg:items-end"><label className="block text-sm font-medium text-slate-700">Skill name<input required name="name" placeholder="e.g. Microsoft Excel" className="mt-2 w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm outline-none transition focus:border-slate-950 focus:ring-2 focus:ring-slate-950/5" /></label><label className="block text-sm font-medium text-slate-700">Category<select name="category" defaultValue="Development" className="mt-2 w-full rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm outline-none transition focus:border-slate-950 focus:ring-2 focus:ring-slate-950/5">{SKILL_CATEGORIES.map((category) => <option key={category}>{category}</option>)}</select></label><label className="block text-sm font-medium text-slate-700">Display order<input name="sortOrder" type="number" min="0" step="1" defaultValue="0" className="mt-2 w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm outline-none transition focus:border-slate-950 focus:ring-2 focus:ring-slate-950/5" /></label><button type="submit" className="inline-flex h-11 items-center justify-center gap-2 rounded-xl bg-slate-950 px-5 text-sm font-semibold text-white shadow-sm transition hover:bg-slate-800"><Plus size={17} /> Add skill</button></form></section>

    <div className="space-y-6">{SKILL_CATEGORIES.map((category) => { const categorySkills = skills.filter((skill) => skill.category === category); const detail = categoryDetails[category]; const Icon = detail.icon; return <section key={category} className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex flex-col gap-4 border-b border-slate-100 px-5 py-5 sm:flex-row sm:items-center sm:justify-between sm:px-6"><div className="flex items-center gap-4"><span className={`flex h-11 w-11 items-center justify-center rounded-xl ${detail.accent}`}><Icon size={20} /></span><div><h2 className="font-semibold text-slate-950">{category}</h2><p className="mt-0.5 text-sm text-slate-500">{detail.description}</p></div></div><span className="inline-flex w-fit items-center gap-2 rounded-full bg-slate-100 px-3 py-1.5 text-xs font-semibold text-slate-600"><ListOrdered size={13} /> {categorySkills.length} {categorySkills.length === 1 ? "skill" : "skills"}</span></div>{categorySkills.length ? <div className="divide-y divide-slate-100">{categorySkills.map((skill) => <form key={skill.id} action={updateSkillAction.bind(null, skill.id)} className="grid gap-3 px-5 py-4 sm:px-6 lg:grid-cols-[minmax(0,1fr)_190px_120px_auto_auto] lg:items-end"><input required name="name" defaultValue={skill.name} aria-label={`Skill name for ${skill.name}`} className="rounded-xl border border-slate-200 px-3 py-2.5 text-sm font-medium text-slate-800 outline-none transition focus:border-slate-950 focus:ring-2 focus:ring-slate-950/5" /><select name="category" defaultValue={skill.category} aria-label={`Category for ${skill.name}`} className="rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm outline-none transition focus:border-slate-950">{SKILL_CATEGORIES.map((item) => <option key={item}>{item}</option>)}</select><input name="sortOrder" type="number" min="0" step="1" defaultValue={skill.sortOrder} aria-label={`Display order for ${skill.name}`} className="rounded-xl border border-slate-200 px-3 py-2.5 text-sm outline-none transition focus:border-slate-950" /><button type="submit" className="inline-flex h-10 items-center justify-center gap-2 rounded-xl border border-slate-200 px-3 text-sm font-semibold text-slate-700 transition hover:border-slate-300 hover:bg-slate-50"><Pencil size={15} /> Save</button><button formAction={deleteSkillAction.bind(null, skill.id)} type="submit" className="inline-flex h-10 items-center justify-center gap-2 rounded-xl border border-rose-200 px-3 text-sm font-semibold text-rose-600 transition hover:bg-rose-50"><Trash2 size={15} /> Delete</button></form>)}</div> : <div className="px-5 py-8 text-sm text-slate-500 sm:px-6">No skills yet. Use the add form above to populate this category.</div>}</section>; })}</div>
  </div></div>;
}
